baseURL = "/"
title = "Hack The Box: Cheatsheet"
theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowToc = true
TocOpen = true

[params.homeInfoParams]
Title = "Bookmarks"
Content = "A curated index of tools, docs, cheatsheets, and references for automation, development, security, and penetration testing"
